name: Bug Report 🐞
description: Reporting for any bug in the Project.
title: '[BUG]: '
# labels: ["Up-for-Grabs ✋", "bug 🐛"]
assignees:
  - ''


body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug
      placeholder: Describe the bug you encountered.
    validations:
      required: true


  - type: textarea
    id: changes
    attributes:
      label: Changes
      placeholder: Explain the approach to handle this bug.
    validations:
      required: false


  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots 📷
      placeholder: Write N/A if not available.
    validations:
      required: false
